### ISSUE TITLE
-h args error

### ISSUE THREAD

**Issue by passwa11** [Whoopsunix/PPPYSO#1]
java -jar PPPYSO-1.2.0.jar -h

```
Exception in thread "main" java.lang.NullPointerException
	at com.ppp.JavaClassBuilder.build(JavaClassBuilder.java:28)
	at com.ppp.Scheduler.javaClassMaker(Scheduler.java:52)
	at com.ppp.Scheduler.main(Scheduler.java:45)

```

no -h args  or with --help run well

**Comment by Whoopsunix** [comment]
nice find! Will be fixed in next version.
The help information can still be viewed by using '-h' or '-help', which does not affect usage temporarily.
![image](https://github.com/Whoopsunix/PPPYSO/assets/51756428/9fe5c93c-4cdb-4bd9-aaeb-9c44c10e0e80)

**Comment by passwa11** [comment]
yep
